[package]
name = "dpdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "10.0.0"
nom = "7"
pprof = { version = "0.10", features = ["flamegraph", "criterion"] }
#tokio = { version = "1", features = ["full"] }

[[bin]]
name = "dpsql"
path = "src/dpdb_repl/dpsql.rs"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dpdb"
harness = false
